#!/usr/bin/sh

echo creating upload directory...
mkdir gzotp
echo copying files...
cp {Readme.md,app.js,package.json} gzotp/
echo publishing...
npm publish gzotp
echo removing upload directory...
rm -rf gzotp
echo pushing to github...
git push
